<template>
   <div class="container">
       <div class="flex items-center gap-1.5 md:overflow-hidden">
      <router-link
        to="/"
        class="flex-y-center gap-1 text-dark leading-130 text-sm font-medium transition-300 hover:text-blue group"
      >
        Главная</router-link
      >
      <span class="w-1 h-1 rounded-full bg-gray-400 shrink-0"></span>
      <a
        href=""
        class="pointer-events-none !text-gray-400 transition-300 max-w-full flex-y-center cursor-pointer min-w-max group-last:min-w-[100px] sm:group-last:min-w-[200px] breadcrumb-menu line-clamp-1 whitespace-nowrap text-dark leading-130 text-sm font-medium transition-300 hover:text-blue"
        >Условия использования&nbsp;77.uz</a
      >
    </div>

    <div class="pt-5 pb-16 md:px-4 max-w-3xl mx-auto"><h1 class="text-2xl md:text-3.5xl font-bold leading-130 text-dark max-md:px-4">Условия использования&nbsp;77.uz</h1><div class="p-4 bg-white mt-2.5 static-text"><h1>&nbsp; &nbsp; &nbsp; &nbsp;</h1>

<p style="text-align:justify"><span style="font-size:14px"><span style="font-family:&quot;Times New Roman&quot;"><span style="font-family:'Times New Roman'">&nbsp;1. Условия использования Веб-сайта и мобильного приложения «77.uz», в том числе правила публикации объявлений, а также вопросы, касающиеся, разрешения спорных ситуаций, определяются в данных Правилах. Каждый пользователь нашего веб-сайта и мобильного приложения обязан ознакомиться и согласиться с содержанием, изложенным в Правилах. &nbsp;Настоящие условия использования регулируют отношения между ООО «Web 77» и пользователями, при использовании сайта «www.77.uz» и мобильного приложения «77.uz». Полное и безоговорочное принятие пользователем условий ООО «Web 77»</span>&nbsp;<span style="font-family:'Times New Roman'"><span style="font-family:Times New Roman,Times,serif">является:</span>&nbsp;<span style="font-family:Times New Roman,Times,serif">использования &nbsp;сайта «www.77.uz» и мобильного приложения «77.uz», поиска, просмотра или размещения рекламных объявлений, регистрация на сайте и использования других возможностей сайта «www.77.uz» и мобильного приложения «77.uz».</span></span></span></span></p>

<p style="text-align:justify"><span style="font-size:14px"><span style="font-family:&quot;Times New Roman&quot;"><span style="font-family:'Times New Roman'">&nbsp;2. Объявления, размещенные на Веб-сайте и в мобильном приложении, то есть текстовые и графические материалы, являются объектами авторских прав и прав промышленной собственности ООО «Web 77» и зарегистрированных пользователей. Этот контент не может быть использован каким-либо образом без письменного согласия уполномоченного лица. Сбор и обработка информации и иной информации, размещенной на сайте</span>&nbsp;<span style="font-family:'Times New Roman'"><span style="font-family:Times New Roman,Times,serif">и в мобильном приложении, для передачи третьим лицам на других сайтах и ​​за пределами сети Интернет запрещены. Также запрещено использовать символику сайта и мобильного приложения «77.uz», в том числе графические элементы, без согласия «Web 77».</span></span></span></span></p>

<p style="text-align:center"><span style="font-family:&quot;Times New Roman&quot;"><strong><span style="font-size:14,0000pt"><span style="font-family:'Times New Roman'"><span style="font-family:Times New Roman,Times,serif"><span style="font-size:16px">Правила:</span></span></span></span></strong></span></p>

<p style="text-align:justify"><span style="font-size:14px"><span style="font-family:&quot;Times New Roman&quot;"><span style="font-family:'Times New Roman'">&nbsp;3. Рекламные объявления, размещенные на Веб-сайте и в мобильном приложении «77.uz», предназначены исключительно для информационных целей. Мы не продаем, не покупаем и не предоставляем платные услуги. Покупки, кредиты, возвраты и подобные</span>&nbsp;</span><span style="font-family:Times New Roman,Times,serif">де</span><span style="font-family:&quot;Times New Roman&quot;"><span style="font-family:'Times New Roman'">йствия</span><span style="font-family:'Times New Roman'">&nbsp;<span style="font-family:Times New Roman,Times,serif">осуществляются между рекламодателем и покупателем. Сайт, мобильное приложение 77.uz и ООО «Web 77» не являются стороной сделки и не несут ответственности во всех возможных, вытекающих случаях. За правильность информаций в объявлениях ответственность несет автор</span>&nbsp;<span style="font-family:Times New Roman,Times,serif">этого объявления</span>.</span></span></span></p>

<p style="text-align:justify"><span style="font-size:14px"><span style="font-family:&quot;Times New Roman&quot;"><span style="font-family:'Times New Roman'">&nbsp; 4. </span>&nbsp;<span style="font-family:'Times New Roman'"><span style="font-family:Times New Roman,Times,serif">Для </span></span><span style="font-family:'Times New Roman'"><span style="font-family:Times New Roman,Times,serif">просмотра</span></span><span style="font-family:'Times New Roman'">&nbsp;<span style="font-family:Times New Roman,Times,serif">объявлений на сайте и мобильном приложении «77.uz» регистрация не требуется. Наш сайт и мобильное приложение </span></span><span style="font-family:'Times New Roman'"><span style="font-family:Times New Roman,Times,serif">могут использоват</span></span><span style="font-family:'Times New Roman'">&nbsp;<span style="font-family:Times New Roman,Times,serif">только </span></span><span style="font-family:'Times New Roman'"><span style="font-family:Times New Roman,Times,serif">дееспособные лица</span></span>&nbsp;<span style="font-family:'Times New Roman'"><span style="font-family:Times New Roman,Times,serif">старше 18 лет. Использование нашего веб-сайта и мобильного приложения осуществляется при условии соблюдения и принятия наших условий использования. Вы можете</span></span><span style="font-family:'Times New Roman'">&nbsp;<span style="font-family:Times New Roman,Times,serif">только</span></span><span style="font-family:'Times New Roman'">&nbsp;<span style="font-family:Times New Roman,Times,serif">ознакомиться с объявлениями</span>&nbsp;<span style="font-family:Times New Roman,Times,serif">на нашем сайте и в мобильном приложении, а все дальнейшие действия по покупке должны осуществляться без вмешательства «Web 77», в соответствии с законодательством Республики Узбекистан.</span></span></span></span></p>

<p style="text-align:justify"><span style="font-size:14px"><span style="font-family:&quot;Times New Roman&quot;"><span style="font-family:'Times New Roman'">&nbsp;5. Мы собираем неличную информацию о вашем взаимодействии с веб-сайтом, такую ​​как ваш IP-адрес, тип браузера, операционная система, информация об устройстве и посещенные страницы. Мы используем файлы cookie и аналогичные технологии, чтобы проанализировать модели использования и собрать статистическую информацию.</span></span></span></p>

<p style="text-align:justify"><span style="font-size:14px"><span style="font-family:&quot;Times New Roman&quot;"><span style="font-family:'Times New Roman'">&nbsp;6. Для </span><span style="font-family:'Times New Roman'"><span style="font-family:Times New Roman,Times,serif">создание объявлений</span></span><span style="font-family:'Times New Roman'">&nbsp;<span style="font-family:Times New Roman,Times,serif">на веб-сайте и в мобильном приложении «77.uz» необходимо зарегистрироваться. </span></span><span style="font-family:'Times New Roman'"><span style="font-family:Times New Roman,Times,serif">Ч</span></span><span style="font-family:'Times New Roman'"><span style="font-family:Times New Roman,Times,serif">тоби пройти регистрацию</span></span><span style="font-family:'Times New Roman'">&nbsp;<span style="font-family:Times New Roman,Times,serif">ф</span></span><span style="font-family:'Times New Roman'"><span style="font-family:Times New Roman,Times,serif">изические и юридические лица предоставляют нужную</span></span>&nbsp;<span style="font-family:'Times New Roman'"><span style="font-family:Times New Roman,Times,serif">информацию о себе. Они должны быть согласны с тем, что эта информация будет отображаться в объявлениях, размещенных ими на сайте «77.uz» и в мобильном приложении. Зарегистрированные пользователи сайта и мобильного приложения «77.uz» могут создать</span></span>&nbsp;<span style="font-family:'Times New Roman'"><span style="font-family:Times New Roman,Times,serif">объявлении</span></span><span style="font-family:'Times New Roman'">&nbsp;<span style="font-family:Times New Roman,Times,serif">прикрепив изображения продукции.</span></span></span></span></p>

<p style="text-align:justify"><span style="font-size:14px"><span style="font-family:&quot;Times New Roman&quot;"><span style="font-family:'Times New Roman'">&nbsp;7. Зарегистрированные пользователи могут размещать только те товары, которые </span><span style="font-family:'Times New Roman'"><span style="font-family:Times New Roman,Times,serif">есть у них в наличие</span></span><span style="font-family:'Times New Roman'">. Вся информация, указанная в объявлении, должна быть достоверной. Если продукт закончится через некоторое время после публикации то, объявление должно быть удалено. Объявление должно соответствовать законодательству Республики Узбекистан. Запрещается продавать запрещенную законом продукцию, использовать в </span><span style="font-family:'Times New Roman'"><span style="font-family:Times New Roman,Times,serif">информация</span></span><span style="font-family:'Times New Roman'"><span style="font-family:Times New Roman,Times,serif">х </span></span><span style="font-family:'Times New Roman'">&nbsp;<span style="font-family:Times New Roman,Times,serif">о </span></span><span style="font-family:'Times New Roman'"><span style="font-family:Times New Roman,Times,serif">продукции слова и медиафайлы, противоречащие закону и морали. Пользователь, создавший объявление, несет полную ответственность за любые споры, которые могут возникнуть с объявлением, и за любые нарушения действующего законодательства.</span></span></span></span></p>

<p style="text-align:justify"><span style="font-size:14px"><span style="font-family:&quot;Times New Roman&quot;"><span style="font-family:'Times New Roman'">&nbsp;8. По требованию пользователей вся информация о них будет полностью удалена с сайта и мобильного приложения «77.uz». Администрация сайта и мобильного приложения «77.uz» имеет право удалять <span style="font-family:Times New Roman,Times,serif">объявления</span>, не соответствующую внутренним правилам, блокировать пользователей и удалять их полностью без каких-либо объяснений и предупреждений.</span></span></span></p>

<p style="text-align:justify"><span style="font-size:14px"><span style="font-family:&quot;Times New Roman&quot;"><span style="font-family:'Times New Roman'">&nbsp;9. Все споры между «Web 77» и зарегистрированными пользователями разрешаются в соответствии с вышеуказанными условиями использования. Споры между всеми пользователями сайта и мобильного приложения «77.uz», а также между иными третьими лицами разрешаются без участия «Web 77».</span></span></span></p>

<p style="text-align:justify"><span style="font-size:14px"><span style="font-family:Calibri"><span style="font-family:'Times New Roman'">&nbsp;10. «Web 77» имеет право улучшать и изменять <span style="font-family:Times New Roman,Times,serif">условия использования</span>&nbsp;<span style="font-family:Times New Roman,Times,serif">в любое время без уведомления пользователей. Пользователь несет ответственность за регулярное ознакомление с текущей версией Условий использования. Новые условия вступают в силу с момента внесения поправок.</span></span></span></span></p>

<h1>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</h1></div></div>
    </div> 
</template>
<script setup>

</script>